### ISSUE TITLE
[Bug] Bot no longer collects player guesses sent via DM

### ISSUE THREAD

**Issue by rgroves** [Fubinator/planning-poker-discord-bot#65]
In [commit de8dfb1c](https://github.com/Fubinator/planning-poker-discord-bot/commit/de8dfb1cea8e13d3d6d80c92076e3dcbf306c197) the logic which calls Poker.addAnswer was removed from src/client.js (lines 54-56), but no logic was added back in to handle collecting the guesses that players DM to the bot.

A test should be added so that it checks that the guesses are recapped in "end of round" message as it was in the version of the code prior to the changes in de8dfb1c.

Given the way client.js was refactored into commands, we can continue using that same pattern and require players to include a command in their DM with their story points guess. I propose the following:

`!answer <points>`

If you agree with this, please assign this issue to me as I'd like to fix it since I'm familiar with the bug as discovered when I was working on Issue #4, which I first noted in the PR #64 ([in this comment](https://github.com/Fubinator/planning-poker-discord-bot/pull/64#issuecomment-705750412)).

**Comment by Fubinator** [comment]
First of all, sorry for the very late reply. I had little time and lost interest in the project for a while, since I didn't need the bot myself anymore.

Thank you for this detailed description of the bug.
With the introduction of multiple games at the same time, the old logic could not work at all anymore, because it is not clear for which game the storypoints are given. I added with #86 that users have to register for a game. This allows me to put the old logic back in by picking the correct game.

With your description of the problem I was able to resolve the issue quickly. Thanks again!
